### PR TITLE
Handle bools

### LINKED ISSUE #94: Getting logical types into Oct2Py
The following fails on 3.5.9:

``` python
import oct2py
import numpy as np
engine = oct2py.Oct2Py(convert_to_float=False)
assert engine.islogical(np.array([0, 1], dtype='bool'))
```

What's the correct method for passing logicals into Oct2Py?
Thanks!

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #94.

This is done, but I'll wait for #100 and #105 to merge this since it is an API change, then release 4.0.

### CODE REVIEW

**Comment by blink1073** [comment]
Closing because `bool` handling is only available in `scipy >= 0.16`.

**Comment by brianthelion** [comment]
References https://github.com/scipy/scipy/issues/4022.

**Comment by blink1073** [comment]
Revisiting this for 4.0 release, cf #103.

**Comment by blink1073** [comment]
Dev note: scipy 0.17 is working and is available on Ubuntu 16.04, that seems like a reasonable threshold.

**Comment by blink1073** [comment]
This is done, but I'll wait for #100 and #105 to merge this since it is an API change, then release 4.0.

**Comment by blink1073** [comment]
I'm going to do this as part of #108.

**Pull request closed without merging**
