### PR TITLE
Handle dynamic classes

### LINKED ISSUE #80: Octave Classes unusable from Python
Consider the following example

``` .py
>>> oc.addpath(oc.genpath('E:\MNPBEM13f2'))
>>> oc.push(['diameter','Hs'],[diameter,Hs])
>>> oc.eval('g0=trisphere(256, diameter);')
>>> oc.eval('class(g0)')
ans = particle
u'particle'
>>> g0 = oc.trisphere(256, diameter)
>>> type(g0)
oct2py.utils.Struct
>>> oc.eval('methods(g0)')
Methods for class particle:

clean      flip       norm       ploto      select     vertcat
display    flipfaces  particle   rot        shift      vertices
dist       interp     plot       scale      subsref
>>> dir(g0)
['__class__', '__cmp__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_is_allowed', 'area', 'clear', 'copy', 'faces', 'fromkeys', 'get', 'has_key', 'items', 'iteritems', 'iterkeys', 'itervalues', 'keys', 'pop', 'popitem', 'pos', 'setdefault', 'update', 'values', 'vec', 'verts', 'viewitems', 'viewkeys', 'viewvalues']
```

I can't call the classes methods from python, because oct2py returns a Struct Object, 

Why Can't a dynamic python Class be created.

`__getattr__`, and `__getitem__` can be mapped to octave.  

hence

``` .py
>>> g1 = oc.eval('shift(g0, [Hs, 0, 0])')
```

would be the same as

``` .py
>>> g1 = g0.shift(np.array([Hs, 0, 0]))
```

Pesudocode for `__getattr__`

``` .py
def __getattr__(self,name)
    if name in self.methods:
         return self.octave.getmethod(self.var, name)
    elif name in self.attrs:
        return self.octave.getattr(self.var, name)
    else:
         raise AttributeError
```

Attributes could also be accessed as a dict like Struct, but not methods.

`getmethod` should return a function that calls octave like

```
name(var, *args, **kwargs)
```

Converting `*args`, and `**kwargs` to octave format

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #80.  Also cleans up dynamic method handling and makes sure all methods have a nice `repr` and `help`.

Example:

```python
from oct2py import octave
p = octave.polynomial([1,2,3])
p.display(verbose=True)  # prints the nice display of the polynomial
p.poly  # prints the array
```

### CODE REVIEW

**Comment by blink1073** [comment]
Released as `3.8`.

**Comment by kubark42** [comment]
The given example doesn't work. It seems that octave doesn't have a `polynomial` class built in. I'm having trouble getting my classes to work, and was looking for a canonical test that I have set up python, oct2py, and octave correctly. Is there a built-in class which could be used as a test example?

**Comment by blink1073** [comment]
Hi @kubark42, the polynomial example is from the [Octave documentation](https://www.gnu.org/software/octave/doc/v4.0.3/Creating-a-Class.html) and is also used in the oct2py [test suite](https://github.com/blink1073/oct2py/tree/master/oct2py/tests/%40polynomial).    I don't believe there are any built in objects in the default Octave install.

**Comment by kubark42** [comment]
@blink1073 Gotcha, thanks! I'll take a look at it. 

I made my class functions work through the `eval()` method. That seems to work pretty well for what I was doing.

**Pull request merged**
