### PR TITLE
Fix column vector

### PR DESCRIPTION
**Pull request by yasirroni**
I haven't run the test. How to run the test?

___

I vote to make atleast2d as default since that is what octave do. Furthermore, passing cell from octave to python already got auto squeze in the other part of the code(?), so we can remove the hardcoded squeeze in python part of Cell?

### CODE REVIEW

**Comment by yasirroni** [comment]
Fix https://github.com/blink1073/oct2py/issues/221

**Comment by blink1073** [comment]
You can run locally by installing and running `pytest` from the repo root.

**Comment by blink1073** [comment]
Kicking CI

**Comment by yasirroni** [comment]
It throws error in this test:

```python
def test_singleton_sparses(self):
    '''Make sure a singleton sparse matrix works'''
    import scipy.sparse
    data = scipy.sparse.csc.csc_matrix(1)
    self.oc.push('x', data)
    assert np.allclose(data.toarray(), self.oc.pull('x').toarray())
    self.oc.push('y', [data])
    y = self.oc.pull('y')
    assert np.allclose(data.toarray(), y[0].toarray()) # here
```

**Comment by yasirroni** [comment]
Maybe make Cell behave like octave matrix, if called using single index than return **single** value from flatten matrix with order of column vector?

We can modify the __getitem__ method

**Comment by blink1073** [comment]
> We can modify the getitem method

I like that idea!

**Comment by yasirroni** [comment]
The latest commit support MATLAB style iteration based on column vector indexing.

___

Problem is, whenever we want to push any type data, A Cell is created and pushing a single value with n*m dimension will make scipy trying to push None type and error. I don't know how to fix that.

**Comment by yasirroni** [comment]
> I like that idea!

Done!

This code implement Cell that support MATLAB indexing, so that it is based on Column Vector, not Row Vector.
___
But, iterator on `ravel()` will use numpy indexing that based on Row Vector.

**Comment by yasirroni** [comment]
Another fix, another bug. .__.

Maybe, we just need to make atleast2d and handle special case of [0]

**Comment by blink1073** [comment]
> Maybe, we just need to make atleast2d and handle special case of [0]

Yeah that sounds right

**Comment by yasirroni** [comment]
Downgraded in functionality to https://github.com/blink1073/oct2py/pull/225

**Pull request closed without merging**
